apiVersion: v1
kind: Secret
metadata: 
  name: config-secret
  namespace: magento
type: Opaque
data: 
  DB_PASS: c2VjcmV0
  DB_ROOT_PASS: c3VwZXJzZWNyZXQ=
  KEY: MmI1MDJjNjRjMDBiNWJjNzgxNGMwZTI1ODU1YmU5ZGY=
  ADMIN_PASSWORD: dGhpc2lzYXJhbmRvbXN0cmluZw==
---
apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: magento
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJ5b3VybmFtZXNwYWNlLmF6dXJlY3IuaW8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJ5b3VydXNlcm5hbWUiLAogICAgICAicGFzc3dvcmQiOiAieW91cnBhc3N3b3JkIiwKICAgICAgImVtYWlsIjogInlvdXJlbWFpbEBkb21haW4uY29tIiwKICAgICAgImF1dGgiOiAieW91cmF1dGhrZXkiCiAgICB9CiAgfQp9
---
apiVersion: v1
kind: Secret
metadata:
  name: yoursslcertname
  namespace: magento
  uid: bda865b7-b884-472f-afd2-85b066409dbf
type: kubernetes.io/tls
data:
  tls.crt: base64encoded_your_ssl_cert
  tls.key: base64encoded_your_ssl_private_key