apiVersion: v1
data:
  my.cnf: |
    # Copyright (c) 2014, 2021, Oracle and/or its affiliates.
    #
    # This program is free software; you can redistribute it and/or modify
    # it under the terms of the GNU General Public License, version 2.0,
    # as published by the Free Software Foundation.
    #
    # This program is also distributed with certain software (including
    # but not limited to OpenSSL) that is licensed under separate terms,
    # as designated in a particular file or component or in included license
    # documentation.  The authors of MySQL hereby grant you an additional
    # permission to link the program and your derivative works with the
    # separately licensed software that they have included with MySQL.
    #
    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License, version 2.0, for more details.
    #
    # You should have received a copy of the GNU General Public License
    # along with this program; if not, write to the Free Software
    # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA

    #
    # The MySQL  Server configuration file.
    #
    # For explanations see
    # http://dev.mysql.com/doc/mysql/en/server-system-variables.html

    [mysqld]
    default_authentication_plugin   = mysql_native_password
    secure_file_priv                = NULL
    datadir         = /var/lib/mysql
    innodb_buffer_pool_size = 8G
    innodb_flush_log_at_trx_commit = 0
    sync_binlog = 0
    innodb_flush_method = O_DIRECT
    innodb_buffer_pool_instances = 8
    innodb_thread_concurrency = 0
    innodb_stats_on_metadata = OFF
    innodb_buffer_pool_dump_at_shutdown = ON
    innodb_buffer_pool_load_at_startup = ON
    innodb_adaptive_hash_index_parts = 8
    table_open_cache_instances = 16
    innodb_read_io_threads = 16
    innodb_write_io_threads = 16
    innodb_flush_neighbors= 0
    join_buffer_size = 4096K
    sort_buffer_size = 4096K
    max_heap_table_size = 4G
    tmp_table_size = 4G
    table_open_cache = 2048
    table_definition_cache = 4096
    max_connections = 512
    transaction-isolation = READ-COMMITTED
    innodb_lru_scan_depth = 256
    log_bin_trust_function_creators = 1
kind: ConfigMap
metadata:
  name: mysql-config-data
  namespace: magento
