apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: magento
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi-premium #https://learn.microsoft.com/en-us/azure/aks/concepts-storage#storage-classes
  resources:
    requests:
      storage: 128Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: magento-azurefile
  namespace: magento
provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=33
  - gid=33
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Premium_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-azurefile
  namespace: magento
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: magento-azurefile
  resources:
    requests:
      storage: 100Gi
